- id: go-vulncheck
  name: Go Vulnerability Check
  entry: go-vulncheck.sh
  language: script
  always_run: true
  pass_filenames: false
  description: >
    Check for known vulnerabilities in Go dependencies.
    It requires govulncheck executable to be installed.
- id: go-nil-pointer-check
  name: Go Nil Pointer Dereference Check
  entry: go-nilaway.sh
  language: script
  files: ^.*\.go$
  pass_filenames: false
  description: >
    Use Uber Nilawat to detect whether code has nil pointer dereference.
    It requires nilaway executable to be installed.
